# Generated by Django 5.0.6 on 2024-07-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iiifmanifest',
            name='file',
            field=models.FileField(default='uploads/manifest.json', upload_to='uploads/'),
        ),
    ]
